# command: docker-compose -f stack.yml up

version: '3.1'

services:

  # Use root/example as user/password credentials
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongodb-data:/data/db